name: Publishing NPM package

on:
  push:
    branches: [master]
  # pull_request:
  #   branches: [master]
  # rebuild
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Install dependencies
        uses: bahmutov/npm-install@v1

      - name: Clean
        run: yarn clean

      - name: Build app
        run: yarn build

      # - run: npm prepublishOnly
      - uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.ACTION_PUBLISH_TOKEN }}
