name: Publishing NPM package

on:
  push:
    branches: [master]
  # pull_request:
  #   branches: [master]
  # rebuild
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      # - uses: actions/setup-node@v1
      #   with:
      #     node-version: 12
      # - run: npm install
      # - run: npm run build
      - name: Install dependencies
        uses: bahmutov/npm-install@v1

      - name: Build data
        run: yarn build

      # - run: npm prepublishOnly
      - uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.ACTION_PUBLISH_TOKEN }}
